[project]
name = "streamlit-app"
requires-python = "~=3.11.0"
version = "0.0.1"
description = ""
dependencies = [
    "streamlit>=1.42",
    "Authlib>=1.3.2",
    "psycopg[binary]",
    "python-dotenv",
    "openpyxl"
]

[tool.uv]
constraint-dependencies = ["numba>=0.56.0"]
exclude-newer = "7 days"

